name: build-windows
on:
  workflow_dispatch: null

jobs:
  build-windows:
    name: Build demucs-cxfreeze for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: pip install torch==2.7.1 torchaudio==2.7.1 --index-url https://download.pytorch.org/whl/cu128
      - run: pip install cx_Freeze SoundFile dora-search einops "julius>=0.2.3" lameenc openunmix pyyaml tqdm
      - run: cxfreeze freeze_entrypoint.py --target-dir=demucs-cxfreeze-win-cuda --target-name=demucs-cxfreeze --packages=demucs,torch,numpy --includes=numpy._core._multiarray_umath,numpy.core._multiarray_umath
      - run: Invoke-WebRequest -Uri https://www.7-zip.org/a/7zr.exe -OutFile 7zr.exe
      - run: Invoke-WebRequest -Uri https://www.7-zip.org/a/7z2201-x64.exe -OutFile 7zInstaller-x64.exe
      - run: .\7zr.exe x "7zInstaller-x64.exe"
      - run: .\7z.exe a -m0=lzma2 -mmt=on -mx=9 "demucs-cxfreeze-win-cuda.7z" "demucs-cxfreeze-win-cuda"
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.sha }}
          files: demucs-cxfreeze-win-cuda.7z
