name: build-mac
on:
  workflow_dispatch: null

jobs:
  build-mac:
    name: Build demucs-cxfreeze for macOS
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: pip install "numpy<2"
      - run: pip install torch==2.2.2 torchaudio==2.2.2
      - run: pip install cx_Freeze SoundFile dora-search einops "julius>=0.2.3" lameenc openunmix pyyaml tqdm
      - run: cxfreeze freeze_entrypoint.py --target-dir=demucs-cxfreeze-mac --target-name=demucs-cxfreeze --packages=demucs,torch,numpy --includes=numpy._core._multiarray_umath,numpy.core._multiarray_umath
      - run: ditto -c -k --sequesterRsrc --keepParent demucs-cxfreeze-mac demucs-cxfreeze-mac.zip
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.sha }}
          files: demucs-cxfreeze-mac.zip
